[workspace]

members = ["maelstrom", "maelstrom_csp", "maelstrom_csp2", "challenge1", "challenge1_old", "challenge2", "challenge2_old", "challenge3", "challenge4", "challenge5", "message_macro"]
resolver = "2"
