[package]
name = "challenge1_old"
version = "0.1.0"
edition = "2021"

[dependencies]
maelstrom = { path = "../maelstrom" }

env_logger = "^0.10.1"
futures = "^0.3.30"
log = "^0.4.20"
serde_json = "^1.0.108"
tokio = { version = "^1.35.1", features = ["rt-multi-thread"] }
