#!/usr/bin/env bash

set -euo pipefail

CHALLENGE="$1"
BIN_NAME="challenge${CHALLENGE}"
BIN_PATH="target/release/${BIN_NAME}"

cargo build -p "$BIN_NAME" --release
if [ "$CHALLENGE" == "1" ] ; then
	maelstrom test -w echo --bin "$BIN_PATH" --node-count 1 --time-limit 10
elif [ "$CHALLENGE" == "2" ] ; then
	maelstrom test -w unique-ids --bin "$BIN_PATH" --time-limit 30 --rate 1000 --node-count 3 --availability total --nemesis partition
elif [ "$CHALLENGE" == "3" ] ; then
    maelstrom test -w broadcast --bin "$BIN_PATH" --node-count 25 --time-limit 20 --rate 100 --latency 100
elif [ "$CHALLENGE" == "4" ] ; then
    maelstrom test -w g-counter --bin "$BIN_PATH" --node-count 3 --rate 100 --time-limit 20 --nemesis partition
elif [ "$CHALLENGE" == "5" ] ; then
    maelstrom test -w kafka --bin "$BIN_PATH" --node-count 2 --concurrency 2n --time-limit 20 --rate 1000
else
	echo "Unknown challenge: $CHALLENGE"
	exit 1
fi
